# Vectorisation
___

## Theory

Whether operating on CPU or GPU, vectorisation may be covered by SIMD - single instruction, multiple data.

## Proofs
To confirm that vectorisation is good, mmkay.

In [1]:
import numpy as np
import math

### A simple multiplication

In [2]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [3]:
%%timeit
c = np.dot(a, b)

1.79 ms ± 88.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%%timeit
c = 0
for i in range(1000000):
    c += a[i]*b[i]

310 ms ± 1.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Matrix multiplication

For a matrix multiplication, where $u=Av$, we can calculate it as $u_i = \Sigma_{j}A_{ij}v_{j}$.

So this can be implemented as:
```
u = np.zeros((0,1))
for i ...
    for j ...
        u[i] += A[i][j]*v[j]
```

But we'd prefer to vectorise - something more like:

```
u = np.dot(A, v)
```

Or, consider if we had some vector, $v$, and we wanted to raise it an exponential.

In [5]:
v = np.random.rand(1000000)

We could do it with a for-loop:

In [6]:
u = np.zeros(v.shape)

In [7]:
%%timeit
for i in range(u.shape[0]):
    u[i] = math.exp(v[i])

393 ms ± 4.84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Or just do a vector multiply:

In [8]:
%%timeit
u = np.exp(v)

17.4 ms ± 33.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Broadcasting

### Demonstrate addition

In [9]:
a = np.random.randn(2, 3)
b = np.random.randn(2, 1)

In [10]:
print(a)
print(b)

[[-0.49799754 -0.09606081  0.97080204]
 [-1.01471902  1.62492704 -0.34849449]]
[[-0.51888195]
 [ 1.32111376]]


In [11]:
print(a+b)

[[-1.0168795  -0.61494276  0.45192008]
 [ 0.30639474  2.94604079  0.97261927]]


### Demonstrate multiplication - sans broadcasting

In [13]:
c = np.random.randn(4, 3)
d = np.random.randn(3, 2)

In [14]:
print(c*d)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

### Demonstrate benefits of vectorisation

In [32]:
e = np.random.randn(3, 4)
f = np.random.randn(4, 1)

In [18]:
%%timeit
g = np.zeros((3, 4))
for i in range(3):
    for j in range(4):
        g[i][j] = e[i][j] + f[j] 

26.8 µs ± 777 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
print(g)

[[ 0.67716591 -3.278552   -0.83960081 -1.78762101]
 [ 0.01913412 -3.37616193 -1.28469314 -1.48787126]
 [-0.93570334 -1.53201769 -2.25130636 -2.37985336]]


In [20]:
%%timeit
g = e + f.T

2.49 µs ± 25.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
print(g)

[[ 0.67716591 -3.278552   -0.83960081 -1.78762101]
 [ 0.01913412 -3.37616193 -1.28469314 -1.48787126]
 [-0.93570334 -1.53201769 -2.25130636 -2.37985336]]


### Broadcasting and element-wise multiplication

In [24]:
h = np.random.randn(3, 3)
i = np.random.randn(3, 1)
j = h*i

In [25]:
j.shape

(3, 3)

In [26]:
h

array([[-0.27454827, -1.19386305,  0.26199524],
       [-1.78268522,  0.2699331 , -1.62372749],
       [ 2.9111836 ,  0.67288493, -0.75138777]])

In [27]:
i

array([[ 0.60287052],
       [ 0.90737974],
       [-0.42985824]])

In [28]:
j

array([[-0.16551706, -0.71974484,  0.15794921],
       [-1.61757246,  0.24493182, -1.47333743],
       [-1.25139626, -0.28924513,  0.32299023]])

### Matrix multiplication

In [29]:
k = np.random.randn(12288, 150)
l = np.random.randn(150, 45)
m = np.dot(k, l)

In [30]:
m.shape

(12288, 45)